config/routes.rb
Rails.application.routes.draw do
  # root 'special_pages#home'
  root 'special_pages#home2'
  get 'home' => 'special_pages#home2', as: :home
  get 'home2' => 'special_pages#home2' #, as: :home
  get 'home3' => 'special_pages#home'
  get 'about' => 'special_pages#about', as: :about
  get 'tech' => 'special_pages#technical', as: :tech
  resources :newsposts do
    resources :news_comments
  end
  resources :news_tags do
    resources :newsposts, only: %i[index]
  end
  get 'tags/:id/add' => 'tags#add_fave', as: :add_fave #, constraints: { id: /[^\/]+/ }
  get 'tags/:id/remove' => 'tags#remove_fave', as: :remove_fave #, constraints: { id: /[^\/]+/ }
  resources :tags do #, constraints: { id: /[^\/]+/ } do
    resources :stories, only: %i[index]
  end
  resources :characters do
    resources :stories, only: %i[index]
  end

  get 'sources/bulk_update' => 'sources#update_form', as: :bulk
  post 'sources/bulk_update' => 'sources#update_receiver'
  get 'sources/search' => 'sources#search_form', as: :source_search
  get 'sources/results' => 'sources#search_results'
  resources :sources, only: [:new] #, constraints: { id: /[^\/]+/ }
  get 'sources/:type', to: 'sources#index_type', constraints: { type: /[a-z_]+/ }, as: :type
  resources :sources do
    resources :stories, only: %i[index]
  end

  get 'stories/:id/chapters/all' => 'stories#showall'
  get 'stories/:id/all' => 'stories#showall', as: :story_all
  get 'stories/:id/navigate' => 'stories#navigate', as: :chap_nav
  # get 'stories/:id/tags' => 'stories#tag_list', constraints: lambda { |req| req.format == :json }
  # get 'stories/:id/chapters/:chapter_num' => 'stories#show_chapter'
  # get 'stories/:id/add_bookmark' => 'bookmarks#new'
  get 'stories/search' => 'stories#search', as: :story_search
  post 'stories/search_results' => 'stories#search_results'
  get 'stories/search_results' => 'stories#search_results', as: :story_s_res
  resources :stories do
    member do
      post 'multi_update'
    end
    resources :chapters do
      # collection do
      member do
        if Rails.env.development? || ENV["MULTI_CHAPTER_UPDATE"]
          get 'multi_update'
          # post 'multi_update' => 'stories#multi_receiver'
        end
      end
    end
    resources :comments
    resources :bookmarks, except: [:show]
  end
  resources :bookmarks, only: [:index]
  # resources :chapters, only: %i[index create]

  # get 'stories/:story_id/add' => 'chapters#new'
  # get 'stories/:story_id/edit_chapter/:chapter_num' => 'chapters#edit'
  # post 'stories/:story_id' => 'chapters#create'
  # match 'stories/:story_id/:chapter_num' => 'chapters#update', via: %i[patch put]

  # get '/user_confirm/:user_name/auth=:hash' => 'users#confirm'
  get 'users/:id/auth=:hash' => 'users#confirm', constraints: { id: /[^\/]+/ }
  get 'login' => 'users#login', as: :login
  post 'login' => 'users#login_receiver'
  get 'register' => 'users#register', as: :register
  get 'logout' => 'users#logout', as: :logout
  match 'users/:id/deactivate' => 'users#deactivate', via: %i[patch put], as: :deactivate #, constraints: { id: /[^\/]+/ }
  delete 'users/:id/ban' => 'users#ban', as: :ban #, constraints: { id: /[^\/]+/ }
  get 'faves' => 'users#faves', as: :faves
  get 'users/:id/subscribe' => 'users#subscribe', as: :subscribe #, constraints: { id: /[^\/]+/ }
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: :unsubscribe #, constraints: { id: /[^\/]+/ }
  get 'users/subs', as: :subs
  get 'users/forgot_password' => 'users#forgot', as: :forgot
  post 'users/forgot_password' => 'users#forgot_receiver'
  post 'users/:id/:conf' => 'users#reset_receiver', as: :reset_pw
  resources :users, except: [:new], constraints: { id: /[^\/]+/ } do
    member do
      get 'send_confirmation'
    end
    resources :bookmarks, except: %i[new create show]
  end
  # resources :bookmarks

  namespace :admin do
    resources :banned_addresses, only: %i[index destroy],
                                 constraints: { id: /[^\/]+/ }
  end

  # if Rails.env.development?
  #   get 'comments' => 'comments#index_all'
  # end

  get 'search' => 'search#full_form', as: :search
  get 'results' => 'search#results'

  # get 'autocomplete/tag' => 'auto_complete#tag'
  # get 'autocomplete/source' => 'auto_complete#source'
  # get 'autocomplete/character' => 'auto_complete#character'
  get 'autocomplete/:action' => 'auto_complete#%{action}', as: :ac
end

app/models/user.rb
require 'elasticsearch/model'

class User < ApplicationRecord
  include Updateable
  include Nameclean
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  self.primary_key = :name
  has_many :stories,   foreign_key: 'author', primary_key: 'name',
                       dependent: :destroy, after_add: :mail_followers
  has_many :comments,  foreign_key: 'author', primary_key: 'name',
                       dependent: :destroy
  has_many :newsposts, foreign_key: 'admin', primary_key: 'name',
                       dependent: :destroy
  has_many :bookmarks, foreign_key: 'user_name', primary_key: 'name',
                       dependent: :destroy
  has_many :faves, through: :bookmarks, source: :story
  has_many :news_comments, foreign_key: 'author', primary_key: 'name',
                           dependent: :destroy
  has_and_belongs_to_many :tags, join_table: :fave_tags, primary_key: 'name',
                                 foreign_key: 'user_name',
                                 association_foreign_key: 'tag_name'

  has_many :sub_reads, class_name: 'Subscription', foreign_key: 'reader_name',
                       primary_key: 'name'
  has_many :sub_writes, class_name: 'Subscription', foreign_key: 'writer_name',
                        primary_key: 'name'
  has_many :fave_writers, through: :sub_reads, source: :writer
  has_many :fans, through: :sub_writes, source: :reader

  before_save { self.email = email.downcase }
  validates :name,
            presence: { message: " can't be blank." },
            length: { maximum: 50, message: "Name is too long." },
            exclusion: { in: ['guest'] },
            # format: { with: /[^\/]+/,
            #           message: " cannot contain the character '/'" },
            uniqueness: true
  EMAIL_REGEX = /\A[\w+\-\.\+]+@[a-z\d\-\.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  # validates :password, length: { minimum: 8 }
  has_attached_file :avatar,
                    styles: { original: "100x100>" },
                    default_url: "avatars/default_avatar.jpg"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_size :avatar, less_than: 200.kilobytes

  def self.find_by_name(str)
    # super(un_param(str))
    find_by(name: un_param(str))
  end

  def delete_avatar=(del)
    self.avatar = nil if del.to_i == 1
  end

  def delete_avatar
    false
  end

  def mail_followers(story)
    self.fans.each do |fan|
      UserMailMailer.story_created(self, fan, story).deliver_now
    end
  end

  def story_permissions(story)
    if story.user == self
      return { read: true, edit: true, delete: true }
    end
    if self.admin
      return { read: true, edit: false, delete: true }
    end
    answer = { read: true, edit: false, delete: false }
    #todo: handle this correctly when session[:adult] is true
    if story.is_adult? && !self.adult
      answer[:read] = false
    end
    answer
  end

  def can_post?
    self.is_confirmed && !(self.deactivated)
  end

  def visible_stories(other_user)
    get_all = (other_user == self) || other_user.adult
    get_all ? stories : Story.non_adult(stories)
  end

  def visible_bookmarks(other_user)
    other_user == self ? bookmarks : bookmarks.where(private: false)
  end

  def to_partial_path
    'users/summary'
  end

  # def num_bookmarks(can_see_private)
  #   can_see_private ? bookmarks.count : bookmarks.where(private: false).count
  # end

  def self.valid_user?(username)
    return false unless self.exists?(username)
    self.find(username).can_post?
  end

  def self.find_email_by_regex(re_str)
    self.where("email ~* ?", re_str)
  end

  def self.search(query)
    __elasticsearch__.search query: {
      query_string: {
        default_field: 'name',
        default_operator: 'AND',
        query: query
      }
    }
  end

  def get_zone
    ActiveSupport::TimeZone.new(time_zone)
  end

  #paramater is a TimeWithZone
  def time_to_local(twz)
    twz.in_time_zone(get_zone)
  end

  def display_name
    name
  end

  def self.name_field
    :name
  end

end

# User.__elasticsearch__.create_index! force: true
# User.import

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :set_user #, only: %i[show destroy send_confirmation]
  skip_before_action :set_user, only: %i[
    register index create logout login faves subs forgot
  ]
  before_action :check_user, only: %i[deactivate edit update]

  def register
    @page_title = "Register new user"
    @user = User.new
  end

  def login
    @page_title = "Log In"
  end

  def index
    @page_title = "Users"
    @users = is_admin? ? User.all : User.where(is_confirmed: true)
    @users = @users.order(name: :asc).paginate(page: params[:page])
  end

  def show
    @page_title = @user.name
    @viewer = current_user_or_guest
    @stories = @user.visible_stories(@viewer)
                    .order(updated_at: :desc)
                    .paginate(page: params[:page], per_page: 10)
  end

  def edit
    @page_title = "Editing #{@user.name}"
  end

  def update
    pars = params_for_edit

    if pars[:password].size + pars[:password_confirmation].size > 0
      unless @user.authenticate(pars[:old_password])
        @error_message = 'Incorrect password'
      end
    end

    if defined? @error_message
      render :edit #, locals: {error_message: error_message}
    else
      pars.delete(:old_password)
      if @user.update(pars)
        redirect_to @user
      else
        render :edit
      end
    end
  end

  def create
    @user = User.new(params_for_create)
    # if @user.invalid?
    #   render('errors/generic_error', locals: {message: @user.errors.inspect}) && return
    # end
    # if BannedAddress.is_banned?(@user.email)
    #   render('errors/generic_error',
    #          locals: { message: "That email is banned." }) && return
    # end
    @user.confirmation_hash = generate_hash
    if @user.save
      if BannedAddress.is_banned?(@user.email)
        render('errors/generic_error',
               locals: { message: "That email is banned." }) && return
      else
        send_confirmation
      end
      # redirect_to action: index
      # render 'signup_made'
    else
      @page_title = "Sign Up"
      render 'register'
    end
  end

  def send_confirmation
    UserMailMailer.registration_confirm(@user).deliver_now
    #have to do this because sometimes this method is called from create
    render 'send_confirmation'
  end

  def confirm
    @message = ""
    begin
      # @user = User.find(params[:user_name])
      # logger.debug "is_confirmed datatype: #{@user.is_confirmed.class}"
      # if @user.is_confirmed
      #   message = "Error: user #{@user.name} already active."
      # elsif @user.confirmation_hash != params[:hash]
      #   message = "Error: invalid confirmation hash."
      if @user.confirmation_hash != params[:hash]
        @message = "Error: invalid confirmation hash."
      elsif @user.is_confirmed
        render 'reset_password'
        # redirect_to action: 'forgot'  && return
      else
        @message = "User account #{@user.name} activated!"
        @user.is_confirmed = true
        @message = "Could not save" unless @user.save
        login_internal
      end
    rescue ActiveRecord::RecordNotFound
      @message = "Error: no such user."
    end
    # render :confirm, locals: { message: message }
  end

  def login_receiver
    # @user = User.find(params[:user_name])
    if !@user
      @error_message = 'Invalid username'
      render :login #, locals: { error_message: 'Invalid username' }
    elsif !@user.authenticate(params[:password])
      @error_message = 'Invalid password'
      render :login #, locals: { error_message: 'Invalid password' }
    elsif !@user.is_confirmed
      render "not_confirmed"
    elsif @user.deactivated
      render "deactivated"
    else
      login_internal
      redirect_override(@user)
    end
  end

  def logout
    @page_title = "Logged Out"
    session[:user] = nil
  end

  def destroy
    if is_correct_user?(@user)
      unregister
    # elsif is_admin?
      # ban_internal
    else
      # wrong_user(@user, true)
      wrong_user(@user)
    end
  end

  def ban
    check_admin
    ban_internal
  end

  def deactivate
    # if is_correct_user?(@user)
    @user.deactivated = true
    @user.save
    redirect_to action: 'index'
    # else
    #   wrong_user(@user)
    # end
  end

  def faves
    anon_cant(faves_path) && return unless logged_in?
    @user = current_user
    @page_title = "#{@user}'s Favorite Tags"
  end

  def subscribe
    if cu = current_user
      fvs = cu.fave_writers
      unless fvs.include?(@user)
        fvs << @user
      end
    end
    redirect_to session[:return_page]
  end

  def unsubscribe
    if cu = current_user
      fvs = cu.fave_writers
      if fvs.include?(@user)
        fvs.delete(@user)
      end
    end
    redirect_to session[:return_page]
  end

  def subs
    @page_title = "Subscriptions"
    anon_cant(subs_path) && return unless logged_in?
  end

  def forgot
    @page_title = "Forgot Password"
  end

  def forgot_receiver
    @page_title = "Forgot Password"
    if @user.deactivated
      render 'errors/generic_error',
      locals: {message: "Error: Account of user '#{@user.name}' has been deactivated."}
    elsif !@user.is_confirmed
      render 'errors/generic_error',
      locals: {message: "Error: This email address has not yet been confirmed."}
    else
      @user.confirmation_hash = generate_hash
      @user.save
      UserMailMailer.forgot(@user).deliver_now
    end
  end

  def reset_receiver
    unless params[:conf] == @user.confirmation_hash
      redirect_to action: 'confirm'
    end
    if @user.update(params_for_edit)
      redirect_to login_path, notice: "Password updated"
    else
      render action: 'confirm'
    end

  end

  private

  def ban_internal
    @user_name = @user.name
    BannedAddress.add_email(@user.email)
    UserMailMailer.ban_notification(@user).deliver_now
    # @user.destroy
    # User.where(admin: false).find_each do |usr|
    #   if BannedAddress.is_banned?(usr.email)
    # end
    BannedAddress.destroy_users_matching(@user.email)
    render :banned
  end

  def unregister
    @user_name = @user.name
    UserMailMailer.unregistration(@user).deliver_now
    # logger.debug "Stories of user #{@user.name}: #{@user.stories.size}"
    @user.destroy
    render :unregistered
  end

  def login_internal
    session.delete(:adult)
    session[:user] = @user.name
  end

  def set_user
    #do this as find_by rather than find in order to better handle the case
    #where an incorrect username is submitted
    # @user = User.find_by(name: params[:id])
    @user = User.find_by_name(params[:id])
    unless @user
      # @username = params[:id]
      @username = User.un_param(params[:id])
      render 'errors/no_such_user'
    end
    # @was_set_user_called = true
  end

  def check_user
    super(@user)
  end

  def params_for_create
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def params_for_edit
    params.require(:user).permit(:adult, :avatar, :password, :delete_avatar,
                                 :password_confirmation, :old_password,
                                 :time_zone)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # def user_register_path(user)
  #   # "#{request.host_with_port}/user_confirm/#{@user.name}/auth=#{user.confirmation_hash}"
  #   # url_for(action: 'confirm', controller: 'users', only_path: false,
  #           # trailing_slash: true) + "#{@user.name}/auth=#{user.confirmation_hash}"
  #   #todo: figure out how not to hardcode in the host
  #   user_url(user.name, host: '0.0.0.0:3000') + "/auth=#{user.confirmation_hash}"
  # end

  # def logged_in?
  #   # ApplicationController.logged_in?
  #   User.exists?(session[:user])
  # end

  # def user_link(user)
  #   link_to(user.name, user)
  # end

  def time_format(twz)
    raw "<span class='time'>#{l current_user_or_guest.time_to_local(twz)}</span>"
  end
end

app/views/users/_icon_link.html.erb
<%= link_to image_tag(user.avatar.url), user %>

app/views/users/_summary.html.erb
<%# pass in user object as 'user' %>
<% user = obj if local_assigns[:obj] %>

<div class = 'user-summary'>
  <%# put it in a div in case the avatar is smaller than normal %>
  <div class = 'icon-container'>
    <%# image_tag user.avatar.url %>
    <%= render 'users/icon_link', user: user %>
  </div>
  <div class = 'details'>
    <h4>
      <% ed_links = [] %>
      <%= name_link user %>
      <% if is_correct_user?(user) %>
        <% ed_links << link_to('edit', edit_user_path(user)) %>
        <% ed_links << link_to('delete account', user, method: :delete,
          data: { confirm: 'Are you sure?' }) %>
        <% ed_links << link_to('deactivate account', deactivate_path(user),
          method: :patch) unless user.deactivated %>
      <% end %>
      <% if is_admin? %>
        <% ed_links << link_to('ban user', ban_path(user), method: :delete,
        data: { confirm: 'Are you sure?' }) %>
      <% end %>
      <% if logged_in? %>
        <% unless is_correct_user?(user) %>
          <% if current_user.fave_writers.include?(user) %>
            <% ed_links << link_to('unsubscribe', unsubscribe_path(user)) %>
          <% else %>
            <% ed_links << link_to('subscribe', subscribe_path(user)) %>
          <% end %>
        <% end %>
      <% end %>
      <% unless ed_links.empty? %>
        (<%= raw ed_links.join(', ') %>)
      <% end %>
    </h4>
    <h5>
      <% links = [] %>
<%
=begin
%>
      <% is_self = is_correct_user?(user) %>
      <% book_num = user.num_bookmarks(is_self) %>
      <% show_all_stories = is_self || can_see_adult? %>
      <% stories = user.stories %>
      <% stories = Story.non_adult(stories) unless show_all_stories %>
<%
=end
%>
      <% cu = current_user_or_guest %>
      <% stories = user.visible_stories(cu) %>
      <% story_num = stories.count %>
      <% bookmarks = user.visible_bookmarks(cu) %>
      <% book_num = bookmarks.count %>
      <% #TODO: test the adult filtering of stories %>
      <% if story_num > 0 %>
        <% links << link_to(pluralize(story_num, 'story'), user_path(user, anchor: 'user-stories')) %>
      <% end %>
      <% if book_num > 0 %>
        <% links << link_to(pluralize(book_num, 'bookmark'), user_bookmarks_path(user)) %>
      <% end %>
      <%= raw links.join(', ') %>
    </h5>
  </div>
</div>

app/views/users/confirm.html.erb
<p><%= @message %></p>

app/views/users/deactivated.html.erb
<p>The account of <%= name_link(@user) %> has been deactivated.</p>

app/views/users/edit.html.erb
<%= render partial: 'misc/error_header' %>

<%= javascript_include_tag "edit_user", "data-turbolinks-track" => "reload" %>

<%= simple_form_for @user do |f| %>
  <%= f.input :adult, label: 'See adult works' %>
  <% #have to use exists? rather than present? in case there were errors
  #submitting the form the first time
  %>
  <% if @user.avatar.exists? %>
    <%= image_tag @user.avatar.url %>
    <%= f.input :delete_avatar, label:'Delete avatar?', as: :boolean %>
  <% end %>
  <%= f.input :avatar, as: :file %>
  <%= f.input :time_zone %>
  <%= f.input :password, label: 'New password', required: false %>
  <%= f.input :password_confirmation, label: 'Confirm new password',
    required: false %>
  <%= f.input :old_password, label: 'Old password', required: false %>
  <%= f.button :submit %>
<% end %>

app/views/users/faves.html.erb
<% @user.tags.each do |tag| %>
  <%= render tag, tag: tag %>
<% end %>

app/views/users/forgot_receiver.html.erb
<p>Password reset email sent.</p>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= page_entries_info(@users) %>
<%= will_paginate(@users, class: 'button-row centered') %>

<% @users.each do |user| %>
  <%= render 'users/summary', user: user %>
<% end %>

<%= will_paginate(@users, class: 'button-row centered') %>

app/views/users/login.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'misc/error_header' %>
<p>All fields are case-sensitive.</p>
<% #todo:https %>
<%= form_tag('login', method: :post) do %>
<%= label_tag(:id, "User Name:") %>
<%= text_field_tag(:id) %>
<%= label_tag(:password, "Password:") %>
<%= password_field_tag(:password) %>
<br>
<%= submit_tag('Log In') %>
<% end %>

<%= link_to "Forgot password?", :forgot %>

app/views/users/not_confirmed.html.erb
<p>You need to confirm your email address before you can log in. If you didn't
  get a confirmation email, check your spam folder. If it's not there, we can
  <%= link_to 'Re-send it', send_confirmation_user_path(@user) %>.</p>

app/views/users/reset_password.html.erb
<%= simple_form_for @user,
  url: reset_pw_path(@user.name, @user.confirmation_hash),
  method: :post do |f| %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, "Reset Password" %>
<% end %>

app/views/users/show.html.erb
<% if is_correct_user?(@user) %>
  <div><%= link_to 'Edit My Profile', edit_user_path(@user) %></div>
<% end %>
<%= image_tag @user.avatar.url %>
<%# cu = current_user_or_guest %>
<dl>
  <dt>Name</dt>
  <dd><%= @user.name %></dd>
  <%# if @user.name == session[:user] %>
  <%# is_self = is_correct_user?(@user) %>
  <% if is_correct_user?(@user) || is_admin? %>
    <dt>Email</dt>
    <dd><%= @user.email %></dd>
  <% end %>
  <dt>Joined</dt>
  <dd><%= time_format(@user.created_at) %></dd>
  <dt><%= link_to 'Bookmarks', user_bookmarks_path(@user) %></dt>
  <dd><%= @user.visible_bookmarks(@viewer).count %></dd>
</dl>
<br>
<% if logged_in? && !is_correct_user?(@user)%>
  <% if @viewer.fave_writers.include?(@user) %>
    <%= link_to 'Unsubscribe', unsubscribe_path(@user) %>
  <% else %>
    <%= link_to 'Subscribe', subscribe_path(@user) %>
  <% end %>
<% end %>
<br>
<% if @user.deactivated %>
<p>This user is no longer active.</p>
<% end %>

<% if @stories.any? %>
  <h1 id='user-stories'>Stories:</h1>
  <%# stories = @user.stories %>
  <%# unless is_self || can_see_adult? %>
    <%# stories = Story.non_adult(stories) %>
  <%# end %>
  <%# @user.visible_stories(cu).each do |story| %>
  <%= page_entries_info(@stories) %>
  <%= will_paginate(@stories, class: 'button-row centered', params: {anchor: 'user-stories'}) %>
  <% @stories.each do |story| %>
    <%= render 'stories/summary', story: story %>
  <% end %>
  <%= will_paginate(@stories, class: 'button-row centered') %>
<% end %>

app/views/users/subs.html.erb
<% current_user_or_guest.fave_writers.each do |user| %>
  <%= render user, user: user %>
<% end %>

app/views/users/unregistered.html.erb
<p>Account of user "<%= @user_name %>" has been deleted.</p>