config/routes.rb
Rails.application.routes.draw do
  # root 'special_pages#home'
  root 'special_pages#home2'
  get 'home' => 'special_pages#home2', as: :home
  get 'home2' => 'special_pages#home2' #, as: :home
  get 'home3' => 'special_pages#home'
  get 'about' => 'special_pages#about', as: :about
  get 'tech' => 'special_pages#technical', as: :tech
  resources :newsposts do
    resources :news_comments
  end
  resources :news_tags do
    resources :newsposts, only: %i[index]
  end
  get 'tags/:id/add' => 'tags#add_fave', as: :add_fave #, constraints: { id: /[^\/]+/ }
  get 'tags/:id/remove' => 'tags#remove_fave', as: :remove_fave #, constraints: { id: /[^\/]+/ }
  resources :tags do #, constraints: { id: /[^\/]+/ } do
    resources :stories, only: %i[index]
  end
  resources :characters do
    resources :stories, only: %i[index]
  end

  get 'sources/bulk_update' => 'sources#update_form', as: :bulk
  post 'sources/bulk_update' => 'sources#update_receiver'
  get 'sources/search' => 'sources#search_form', as: :source_search
  get 'sources/results' => 'sources#search_results'
  resources :sources, only: [:new] #, constraints: { id: /[^\/]+/ }
  get 'sources/:type', to: 'sources#index_type', constraints: { type: /[a-z_]+/ }, as: :type
  resources :sources do
    resources :stories, only: %i[index]
  end

  get 'stories/:id/chapters/all' => 'stories#showall'
  get 'stories/:id/all' => 'stories#showall', as: :story_all
  get 'stories/:id/navigate' => 'stories#navigate', as: :chap_nav
  # get 'stories/:id/tags' => 'stories#tag_list', constraints: lambda { |req| req.format == :json }
  # get 'stories/:id/chapters/:chapter_num' => 'stories#show_chapter'
  # get 'stories/:id/add_bookmark' => 'bookmarks#new'
  get 'stories/search' => 'stories#search', as: :story_search
  post 'stories/search_results' => 'stories#search_results'
  get 'stories/search_results' => 'stories#search_results', as: :story_s_res
  resources :stories do
    member do
      post 'multi_update'
    end
    resources :chapters do
      # collection do
      member do
        if Rails.env.development? || ENV["MULTI_CHAPTER_UPDATE"]
          get 'multi_update'
          # post 'multi_update' => 'stories#multi_receiver'
        end
      end
    end
    resources :comments
    resources :bookmarks, except: [:show]
  end
  resources :bookmarks, only: [:index]
  # resources :chapters, only: %i[index create]

  # get 'stories/:story_id/add' => 'chapters#new'
  # get 'stories/:story_id/edit_chapter/:chapter_num' => 'chapters#edit'
  # post 'stories/:story_id' => 'chapters#create'
  # match 'stories/:story_id/:chapter_num' => 'chapters#update', via: %i[patch put]

  # get '/user_confirm/:user_name/auth=:hash' => 'users#confirm'
  get 'users/:id/auth=:hash' => 'users#confirm', constraints: { id: /[^\/]+/ }
  get 'login' => 'users#login', as: :login
  post 'login' => 'users#login_receiver'
  get 'register' => 'users#register', as: :register
  get 'logout' => 'users#logout', as: :logout
  match 'users/:id/deactivate' => 'users#deactivate', via: %i[patch put], as: :deactivate #, constraints: { id: /[^\/]+/ }
  delete 'users/:id/ban' => 'users#ban', as: :ban #, constraints: { id: /[^\/]+/ }
  get 'faves' => 'users#faves', as: :faves
  get 'users/:id/subscribe' => 'users#subscribe', as: :subscribe #, constraints: { id: /[^\/]+/ }
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: :unsubscribe #, constraints: { id: /[^\/]+/ }
  get 'users/subs', as: :subs
  get 'users/forgot_password' => 'users#forgot', as: :forgot
  post 'users/forgot_password' => 'users#forgot_receiver'
  post 'users/:id/:conf' => 'users#reset_receiver', as: :reset_pw
  resources :users, except: [:new], constraints: { id: /[^\/]+/ } do
    member do
      get 'send_confirmation'
    end
    resources :bookmarks, except: %i[new create show]
  end
  # resources :bookmarks

  namespace :admin do
    resources :banned_addresses, only: %i[index destroy],
                                 constraints: { id: /[^\/]+/ }
  end

  # if Rails.env.development?
  #   get 'comments' => 'comments#index_all'
  # end

  get 'search' => 'search#full_form', as: :search
  get 'results' => 'search#results'

  # get 'autocomplete/tag' => 'auto_complete#tag'
  # get 'autocomplete/source' => 'auto_complete#source'
  # get 'autocomplete/character' => 'auto_complete#character'
  get 'autocomplete/:action' => 'auto_complete#%{action}', as: :ac
end

app/models/tag.rb
require 'elasticsearch/model'
# require 'set'

class Tag < ApplicationRecord
  include Updateable
  include Impliable
  include Storycount
  include Nameclean
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  self.primary_key = :name
  has_and_belongs_to_many :stories, foreign_key: 'name'
  # has_many :aliases, class_name: 'Tag', foreign_key: 'aliased_to'
  # belongs_to :base_tag, class_name: 'Tag'

  has_many :implieds, class_name: 'Implication', foreign_key: 'implier',
                      primary_key: 'name' #, dependent: :destroy
  has_many :implied_tags, through: :implieds, source: :gen_tag, after_add: :update_one_adult

  has_many :impliers, class_name: 'Implication', foreign_key: 'implied',
                      primary_key: 'name' #, dependent: :destroy
  has_many :implying_tags, through: :impliers, source: :spec_tag

  has_and_belongs_to_many :users, join_table: :fave_tags, primary_key: 'name',
                                  foreign_key: 'tag_name',
                                  association_foreign_key: 'user_name'

  after_save :update_desc_adult

  before_destroy :ki_wrapper #:knit_implications

  def update_desc_adult
    if adult
      implied_tags.each do |kid|
        kid.update(adult: true)
      end
    end
  end

  def update_one_adult(kid)
    kid.update(adult: true) if adult
  end

  def ki_wrapper
    knit_implications
    implieds.delete_all
    impliers.delete_all
  end

  def self.find_by_name(str)
    # super(un_param(str))
    find_by(name: un_param(str))
  end

  def tagged_objs
    stories
  end

  # def visible_stories(adult)
  #   adult ? stories : Story.non_adult(stories)
  # end

  def to_partial_path
    'tags/summary'
  end

  # def story_count
  #   if can_see_adult?
  #     return stories.size
  #   else
  #     return stories.count { |s| !s.is_adult? }
  #   end
  # end

  #translates a user-input tag to the form used by the database
  #todo
  def self.tr_to_sql(dirty)
    dirty.downcase
  end

  def display_name
    name
  end

  def self.name_field
    :name
  end

end

# Tag.import
# Tag.__elasticsearch__.create_index! force: true

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # before_action :find_tags, only: [:find]
  before_action :set_tag #, only: %i[show edit update destroy]
  skip_before_action :set_tag, only: %i[index new create search search_results]

  # GET /tags
  # GET /tags.json
  def index
    @page_title = "Most Common Tags"
    tag_set = can_see_adult? ? Tag.all : Tag.where(adult: false)
    @tags = Tag.get_top(tag_set)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @page_title = @tag.name
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  def edit
    @page_title = "Editing #{@tag.name}"
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    pars = params.permit(:adult, :implications, :delete)
    if pars[:delete].present?
      destroy && return
    end
    @tag.adult = pars[:adult].present?
    # @tag.set_adult(pars[:adult].present?)
    if pars[:implications].present?
      failed_imps = @tag.add_imps_by_name(pars[:implications])
    end
    @tag.save
    notice = ''
    if failed_imps.present?
      notice = 'Error: could not add implications for the following tag(s): '
      notice += failed_imps.join(', ')
    end
    redirect_to @tag, notice: notice
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search; end

  def search_results
    @results = Tag.search(params[:q]).records
  end

  def add_fave
    faves = current_user_or_guest.tags
    unless faves.include? @tag
      faves << @tag
    end
    redirect_to session[:return_page]
  end

  def remove_fave
    faves = current_user_or_guest.tags
    if faves.include? @tag
      faves.delete(@tag)
    end
    redirect_to session[:return_page]
  end

  private

  def set_tag
    # @tag = Tag.find_by(name: params[:id])
    @tag = Tag.find_by_name(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :adult)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  # def tags_links(tag_arr, stories)
  #   raw (tag_arr.map do |tag|
  #     link_to(tag.name, stories ? tag_stories_path(tag) : tag)
  #   end.join(', '))
  # end
  def tags_links(tag_arr, stories)
    tagesque_links(tag_arr, 'tag', stories)
  end
end

app/views/tags/_form.html.erb
<%
=begin
%>
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adult %>
    <%= f.check_box :adult %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%
=end
%>
<%= form_tag(@tag, method: :put) do %>
  <dl>
    <dt><%= label_tag(:adult, 'Adult') %></dt>
    <dd><%= check_box_tag(:adult, 1, @tag.adult) %></dd>
    <dt><%= label_tag(:implications, "New Implications") %></dt>
    <dd><%= text_field_tag(:implications) %></dd>
    <dt><%= label_tag(:delete, 'Delete?') %></dt>
    <dd><%= check_box_tag(:delete) %></dd>
  </dl>
  <%= submit_tag 'Update' %>
<% end %>

app/views/tags/_summary.html.erb
<%# tag = obj if obj %>
<% tag = obj if local_assigns[:obj] %>
<div class = "tag-summary">
  <h4><%= name_link tag %></h4>
  <h5>
    <% cse = can_see_adult? %>
    <%# stories = tag.visible_stories(cse) %>
    <% stories = tag.visible_stories(current_user_or_guest) %>
    <% kids = cse ? tag.implied_tags : tag.implied_tags.where(adult: false) %>
    <% parents = cse ? tag.implying_tags : tag.implying_tags.where(adult: false) %>
    <%= link_to pluralize(stories.count, 'story'), tag_stories_path(tag) %>.
    Implies <%= pluralize(kids.count, 'other tag') %>.
    Is implied by <%= pluralize(parents.count, 'other tag') %>.
    <% if is_admin? %>
      <%= link_to 'Edit', edit_tag_path(tag) %>
    <% end %>
    <% if logged_in? %>
      <% if current_user.tags.include?(tag) %>
        <%= link_to 'Remove Favorite', remove_fave_path(tag) %>
      <% else %>
        <%= link_to 'Favorite Tag', add_fave_path(tag) %>
      <% end %>
    <% end %>
  </h5>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>100 Most Common Tags</h1>
<p>
  Tag names are sized according to the popularity of the tag. Hover over a tag
  name to see how many stories have that tag.
</p>
<div class='redlink-container'>
<%# raw cloud_sizer(Tag, @stories, Tag.cloud_names).join(' ') %>
  <%= raw cloud_sizer(@tags, Tag.cloud_names).join(' ') %>
</div>
<%
=begin
%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adult</th>
      <th>Count</th>
      <th>Parents</th>
      <th>Children</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.adult %></td>
        <td><%= tag.stories_count %></td>
        <td><%= tag.implying_tags.count %></td>
        <td><%= tag.implied_tags.count %></td>
        <td><%= link_to 'Show', tag %></td>
        <% if is_admin? %>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>
<%
=end
%>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/search.html.erb
<h1>Find Tags</h1>

<%= form_tag("find", method:"get") do %>
<%= label_tag(:q, "Search tags") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/tags/search_results.html.erb
<% if @results.empty? %>
  No tags found.
<% end %>
<table>
  <% @results.each do |tag| %>
    <tr><td><%= name_link tag %></td></tr>
  <% end %>
</table>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Adult:</strong>
  <%= @tag.adult %>
</p>
<p>
  <strong>Implications:</strong>
  <%= tags_links(@tag.implied_tags, false) %>
</p>
<p>
  <strong>Impliers:</strong>
  <%= tags_links(@tag.implying_tags, false) %>
</p>

<% if logged_in? %>
  <% if current_user.tags.include?(@tag) %>
    <%= link_to 'Remove Favorite', remove_fave_path(@tag) %>
  <% else %>
    <%= link_to 'Favorite Tag', add_fave_path(@tag) %>
  <% end %>
   |
<% end %>
<%= link_to 'Stories', tag_stories_path(@tag) %> |
<% if is_admin? %>
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<% end %>
<%= link_to 'Back', tags_path %>