config/routes.rb
Rails.application.routes.draw do
  # root 'special_pages#home'
  root 'special_pages#home2'
  get 'home' => 'special_pages#home2', as: :home
  get 'home2' => 'special_pages#home2' #, as: :home
  get 'home3' => 'special_pages#home'
  get 'about' => 'special_pages#about', as: :about
  get 'tech' => 'special_pages#technical', as: :tech
  resources :newsposts do
    resources :news_comments
  end
  resources :news_tags do
    resources :newsposts, only: %i[index]
  end
  get 'tags/:id/add' => 'tags#add_fave', as: :add_fave #, constraints: { id: /[^\/]+/ }
  get 'tags/:id/remove' => 'tags#remove_fave', as: :remove_fave #, constraints: { id: /[^\/]+/ }
  resources :tags do #, constraints: { id: /[^\/]+/ } do
    resources :stories, only: %i[index]
  end
  resources :characters do
    resources :stories, only: %i[index]
  end

  get 'sources/bulk_update' => 'sources#update_form', as: :bulk
  post 'sources/bulk_update' => 'sources#update_receiver'
  get 'sources/search' => 'sources#search_form', as: :source_search
  get 'sources/results' => 'sources#search_results'
  resources :sources, only: [:new] #, constraints: { id: /[^\/]+/ }
  get 'sources/:type', to: 'sources#index_type', constraints: { type: /[a-z_]+/ }, as: :type
  resources :sources do
    resources :stories, only: %i[index]
  end

  get 'stories/:id/chapters/all' => 'stories#showall'
  get 'stories/:id/all' => 'stories#showall', as: :story_all
  get 'stories/:id/navigate' => 'stories#navigate', as: :chap_nav
  # get 'stories/:id/tags' => 'stories#tag_list', constraints: lambda { |req| req.format == :json }
  # get 'stories/:id/chapters/:chapter_num' => 'stories#show_chapter'
  # get 'stories/:id/add_bookmark' => 'bookmarks#new'
  get 'stories/search' => 'stories#search', as: :story_search
  post 'stories/search_results' => 'stories#search_results'
  get 'stories/search_results' => 'stories#search_results', as: :story_s_res
  resources :stories do
    member do
      post 'multi_update'
    end
    resources :chapters do
      # collection do
      member do
        if Rails.env.development? || ENV["MULTI_CHAPTER_UPDATE"]
          get 'multi_update'
          # post 'multi_update' => 'stories#multi_receiver'
        end
      end
    end
    resources :comments
    resources :bookmarks, except: [:show]
  end
  resources :bookmarks, only: [:index]
  # resources :chapters, only: %i[index create]

  # get 'stories/:story_id/add' => 'chapters#new'
  # get 'stories/:story_id/edit_chapter/:chapter_num' => 'chapters#edit'
  # post 'stories/:story_id' => 'chapters#create'
  # match 'stories/:story_id/:chapter_num' => 'chapters#update', via: %i[patch put]

  # get '/user_confirm/:user_name/auth=:hash' => 'users#confirm'
  get 'users/:id/auth=:hash' => 'users#confirm', constraints: { id: /[^\/]+/ }
  get 'login' => 'users#login', as: :login
  post 'login' => 'users#login_receiver'
  get 'register' => 'users#register', as: :register
  get 'logout' => 'users#logout', as: :logout
  match 'users/:id/deactivate' => 'users#deactivate', via: %i[patch put], as: :deactivate #, constraints: { id: /[^\/]+/ }
  delete 'users/:id/ban' => 'users#ban', as: :ban #, constraints: { id: /[^\/]+/ }
  get 'faves' => 'users#faves', as: :faves
  get 'users/:id/subscribe' => 'users#subscribe', as: :subscribe #, constraints: { id: /[^\/]+/ }
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: :unsubscribe #, constraints: { id: /[^\/]+/ }
  get 'users/subs', as: :subs
  get 'users/forgot_password' => 'users#forgot', as: :forgot
  post 'users/forgot_password' => 'users#forgot_receiver'
  post 'users/:id/:conf' => 'users#reset_receiver', as: :reset_pw
  resources :users, except: [:new], constraints: { id: /[^\/]+/ } do
    member do
      get 'send_confirmation'
    end
    resources :bookmarks, except: %i[new create show]
  end
  # resources :bookmarks

  namespace :admin do
    resources :banned_addresses, only: %i[index destroy],
                                 constraints: { id: /[^\/]+/ }
  end

  # if Rails.env.development?
  #   get 'comments' => 'comments#index_all'
  # end

  get 'search' => 'search#full_form', as: :search
  get 'results' => 'search#results'

  # get 'autocomplete/tag' => 'auto_complete#tag'
  # get 'autocomplete/source' => 'auto_complete#source'
  # get 'autocomplete/character' => 'auto_complete#character'
  get 'autocomplete/:action' => 'auto_complete#%{action}', as: :ac
end

app/controllers/special_pages_controller.rb
class SpecialPagesController < ApplicationController
  def home
    @page_title = "Home"
  end

  def home2
    @page_title = 'Home'
    @latest_news = Newspost.order(created_at: :desc).limit(3)
  end

  def about
    @page_title = 'About AOC'
  end

  def technical
    @page_title = 'Technical Details'
  end

end

app/helpers/special_pages_helper.rb
module SpecialPagesHelper
end

app/views/special_pages/_autocomplete_script.html.erb
<script>
  <% class_sel = ".#{sing}-input" %>
  <% address = ac_path(sing, format: :json) %>
  $(function(){
    $('<%= class_sel %>').tokenInput('<%= address %>', {
      tokenValue: 'name',
      preventDuplicates: true,
      <% if defined? is_sing %>
        tokenLimit: 1,
      <% end %>
      prePopulate: [
        <% coll.each do |obj| %>
          {name: "<%= obj.is_a?(String) ? obj : obj.name %>"},
        <% end %>
      ]
    });
  });
</script>

app/views/special_pages/_form_helper_errors.html.erb
<%# pass in f (form object), meth (method name as symbol), disp (display name),
type (input type, as symbol), a collection of errors, and optionally an options
hash and/or a div_class string of additional classes for the div
%>

<% options ||= {} %>
<% div_class ||= "" %>
<% div_class += ' field' %>
<% unless errors[meth].empty? %>
  <% div_class += ' field_with_errors' %>
  <% disp += ' ' + errors[meth].join(', ') %>
<% end %>

<div class = "<%= div_class %>" id='<%= meth.to_s + '_edit' %>'>
  <%= f.label(meth, disp) %>
  <%= f.send(type, meth, options) %>
</div>

app/views/special_pages/_form_tag_errors.html.erb
<%# pass in meth (method name as symbol), disp (display name), type (input
type, as symbol), a collection of errors, and optionally an options hash
and/or a div_class string of additional classes to add to the div
%>

<% options ||= {} %>
<% div_class ||= '' %>
<% div_class += ' field' %>
<% unless errors[meth].empty? %>
  <% div_class += ' field_with_errors' %>
  <% disp += ' ' + errors[meth].join(', ') %>
<% end %>

<div class = "<%= div_class %>" >
  <%= label_tag
</div>

app/views/special_pages/about.html.erb
<p>
  This site is a clone of the fanfiction site
  <%= link_to 'Archive of Our Own', 'http://archiveofourown.org/' %>, made by
  Russell Flaum. I created this site both as a demonstration of my abilities,
  and to improve those abilities by practice.
</p>
<h3 id='source'>Where do the stories come from?</h3>
<p>
  Most of the stories on this site are automatically-generated and filled with
  random, meaningless text. A couple are public-domain works by long-dead
  writers, which I copied from
  <%= link_to 'the Gutenberg Project', 'http://www.gutenberg.org/' %>. You can
  identify these by the fact that their summaries include a disclaimer. An
  example of such a story is
  <%= link_to "The Tragedy of Pudd'nhead Wilson", story_path(7) %>. The third category
  contains test stories that I or my beta-testers wrote;
  these mostly consist of random gibberish, and are very short. An example is
  <%= name_link Story.find(Rails.env.production? ? 1 : 2) %>. The final
  category is user-submitted stories. Any logged-in user can submit a story, so
  these can be written by anyone who visits this site &mdash; including you, if you
  choose.
</p>
<h3 id='howto'>How to use this site</h3>
<p>
  Simply <%= link_to 'create an account', register_path %> to get started!
  After registering, you should receive an email asking you to confirm your
  email address (if you don't receive one, check your spam folder). Once you've
  confirmed your address, you can use all the features of the site (except
  those restricted to administrators). For more details on the features
  available, including tagging, searching, commenting, subscribing, bookmarking
  and more, see the <%= link_to 'full feature list', tech_path(anchor: 'feature-list') %>.
</p>

app/views/special_pages/home.html.erb
<ul>
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Stories', stories_path %></li>
<li><%= link_to 'Tags', tags_path %></li>
<li><%= link_to 'News', newsposts_path %></li>
<li><%= link_to 'Bookmarks', bookmarks_path %></li>
<li><%= link_to 'Sources', sources_path %></li>
<li><%= link_to 'Search', search_path %></li>
<li><%= link_to 'Story search', story_search_path %></li>
<li><%= link_to 'Source search', source_search_path %></li>
<li><%= link_to 'Characters', characters_path %></li>
<li><%= link_to 'Newsposts', newsposts_path %></li>
</ul>


<% total = 0 %>
<table>
  <% ActiveRecord::Base.connection.tables.sort.each do |table| %>
  <tr>
    <td><%= table %></td>
    <% sql = "Select count(*) from #{table}" %>
    <% num = ActiveRecord::Base.connection.execute(sql)[0]['count'] %>
    <% total += num %>
    <td><%= number_with_delimiter(num) %></td>
  </tr>
  <% end %>
</table>
<%= number_with_delimiter(total) %> 

<%
=begin
%>
<% #TODO: remove this for production %>
<% [Tag, Source, Character].each do |klass| %>
  <%# klass.reset_stories_count %>
  <% klass.find_each do |obj| %>
    <% if obj.stories_count != obj.stories.count %>
      <%= name_link obj %> <%= obj.stories.count %> <%= obj.stories_count %><br>
    <% end %>
  <% end %>
<% end %>
<%
=end
%>



<%
=begin
%>
<ul>
<% 10.times do %>
  <li>
    <%= raw Forgery(:lorem_ipsum).paragraph(sentences: 20, html: true, random: true) %>
  </li>
<% end %>
</ul>
<%
=end
%>

<%# raw Forgery('lorem_ipsum').paragraphs(5, html: true, sentences: 10) %>

app/views/special_pages/home2.html.erb
<div class='home-container'>
  <div class='browse page-section'>
    <h3 class='heading'>Find your favorites</h3>
    <p>Browse fandoms by media type or favorite some tags to have them
      listed here.</p>
    <ul class='options column_2'>
        <li class = 'fandom'><%= link_to 'All Fandoms', sources_path, class: 'link' %></li>
      <% Source.source_plurals.each do |sym, name| %>
        <li class = 'fandom'>
          <%= link_to name.titleize, type_path(sym), class: 'link' %>
        </li>
      <% end %>
      <% current_user_or_guest.tags.each do |tag| %>
        <li class = 'fandom'>
          <%= link_to tag.name, tag_stories_path(tag), class: 'link' %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class='news-summary page-section'>
    <h3 class='heading'>News
      <span class='sub-link'>
        <%= link_to 'All News', newsposts_path, class: 'link' %>
      </span>
    </h3>
    <ul class='entries'>
      <% @latest_news.each do |post| %>
        <%= render 'newsposts/summary', post: post %>
      <% end %>
    </ul>
  </div>
</div>