config/routes.rb
Rails.application.routes.draw do
  # root 'special_pages#home'
  root 'special_pages#home2'
  get 'home' => 'special_pages#home2', as: :home
  get 'home2' => 'special_pages#home2' #, as: :home
  get 'home3' => 'special_pages#home'
  get 'about' => 'special_pages#about', as: :about
  get 'tech' => 'special_pages#technical', as: :tech
  resources :newsposts do
    resources :news_comments
  end
  resources :news_tags do
    resources :newsposts, only: %i[index]
  end
  get 'tags/:id/add' => 'tags#add_fave', as: :add_fave #, constraints: { id: /[^\/]+/ }
  get 'tags/:id/remove' => 'tags#remove_fave', as: :remove_fave #, constraints: { id: /[^\/]+/ }
  resources :tags do #, constraints: { id: /[^\/]+/ } do
    resources :stories, only: %i[index]
  end
  resources :characters do
    resources :stories, only: %i[index]
  end

  get 'sources/bulk_update' => 'sources#update_form', as: :bulk
  post 'sources/bulk_update' => 'sources#update_receiver'
  get 'sources/search' => 'sources#search_form', as: :source_search
  get 'sources/results' => 'sources#search_results'
  resources :sources, only: [:new] #, constraints: { id: /[^\/]+/ }
  get 'sources/:type', to: 'sources#index_type', constraints: { type: /[a-z_]+/ }, as: :type
  resources :sources do
    resources :stories, only: %i[index]
  end

  get 'stories/:id/chapters/all' => 'stories#showall'
  get 'stories/:id/all' => 'stories#showall', as: :story_all
  get 'stories/:id/navigate' => 'stories#navigate', as: :chap_nav
  # get 'stories/:id/tags' => 'stories#tag_list', constraints: lambda { |req| req.format == :json }
  # get 'stories/:id/chapters/:chapter_num' => 'stories#show_chapter'
  # get 'stories/:id/add_bookmark' => 'bookmarks#new'
  get 'stories/search' => 'stories#search', as: :story_search
  post 'stories/search_results' => 'stories#search_results'
  get 'stories/search_results' => 'stories#search_results', as: :story_s_res
  resources :stories do
    member do
      post 'multi_update'
    end
    resources :chapters do
      # collection do
      member do
        if Rails.env.development? || ENV["MULTI_CHAPTER_UPDATE"]
          get 'multi_update'
          # post 'multi_update' => 'stories#multi_receiver'
        end
      end
    end
    resources :comments
    resources :bookmarks, except: [:show]
  end
  resources :bookmarks, only: [:index]
  # resources :chapters, only: %i[index create]

  # get 'stories/:story_id/add' => 'chapters#new'
  # get 'stories/:story_id/edit_chapter/:chapter_num' => 'chapters#edit'
  # post 'stories/:story_id' => 'chapters#create'
  # match 'stories/:story_id/:chapter_num' => 'chapters#update', via: %i[patch put]

  # get '/user_confirm/:user_name/auth=:hash' => 'users#confirm'
  get 'users/:id/auth=:hash' => 'users#confirm', constraints: { id: /[^\/]+/ }
  get 'login' => 'users#login', as: :login
  post 'login' => 'users#login_receiver'
  get 'register' => 'users#register', as: :register
  get 'logout' => 'users#logout', as: :logout
  match 'users/:id/deactivate' => 'users#deactivate', via: %i[patch put], as: :deactivate #, constraints: { id: /[^\/]+/ }
  delete 'users/:id/ban' => 'users#ban', as: :ban #, constraints: { id: /[^\/]+/ }
  get 'faves' => 'users#faves', as: :faves
  get 'users/:id/subscribe' => 'users#subscribe', as: :subscribe #, constraints: { id: /[^\/]+/ }
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: :unsubscribe #, constraints: { id: /[^\/]+/ }
  get 'users/subs', as: :subs
  get 'users/forgot_password' => 'users#forgot', as: :forgot
  post 'users/forgot_password' => 'users#forgot_receiver'
  post 'users/:id/:conf' => 'users#reset_receiver', as: :reset_pw
  resources :users, except: [:new], constraints: { id: /[^\/]+/ } do
    member do
      get 'send_confirmation'
    end
    resources :bookmarks, except: %i[new create show]
  end
  # resources :bookmarks

  namespace :admin do
    resources :banned_addresses, only: %i[index destroy],
                                 constraints: { id: /[^\/]+/ }
  end

  # if Rails.env.development?
  #   get 'comments' => 'comments#index_all'
  # end

  get 'search' => 'search#full_form', as: :search
  get 'results' => 'search#results'

  # get 'autocomplete/tag' => 'auto_complete#tag'
  # get 'autocomplete/source' => 'auto_complete#source'
  # get 'autocomplete/character' => 'auto_complete#character'
  get 'autocomplete/:action' => 'auto_complete#%{action}', as: :ac
end

app/views/misc/_error_header.html.erb
<% if defined? @error_message %>
  <span class="error"><%= @error_message %></span>
<% end %>

app/views/misc/_fn.html.erb
<%
=begin
%>
<span class = 'absolute-holder'>
  <span class = 'footnote-marker' title = 'Click for more info'><%= marker %></span><span class = 'footnote-body'><span><%= body %></span></span></span>
<%
=end
%>
<%= render 'misc/fn_a', num: num %>
<% footnotes << body %>

app/views/misc/_fn_a.html.erb
<sup id='fnref:<%= num %>'>
  <a href='#fn:<%= num %>' rel='footnote'><%= num %></a>
</sup>

app/views/misc/_fn_b.html.erb
<li class='footnote' id='fn:<%= num %>'>
  <p>
    <%= yield %>
    <a href='#fnref:<%= num %>'>&uarr;</a>
  </p>
</li>

app/views/misc/_footer.html.erb
<div id='footer'>
  <ul class='no-dec column_2'>
    <li>
      <h4>About</h4>
      <ul class = 'no-dec'>
        <li><%= link_to 'What is this site?', about_path %></li>
        <li><%= link_to 'Where do the stories come from?', about_path(anchor: 'source') %></li>
        <li>
          <%= link_to 'How do I use this site?', about_path(anchor: 'howto') %>
        </li>
      </ul>
    </li>
    <li>
      <h4>Technical Details</h4>
      <ul class = 'no-dec'>
        <li><%= link_to 'Technical Overview', tech_path %></li>
        <li><%= link_to 'Features', tech_path(anchor: 'feature-list') %></li>
        <li><%= link_to 'Known Issues', tech_path(anchor: 'bugs') %></li>
        <li><%= link_to 'Unimplemented Features', tech_path(anchor: 'non-features') %></li>
      </ul>
    </li>
  </ul>
</div>

app/views/misc/_header.html.erb
<div id='main-header'>
  <div class='full-width'>
    <a href='<%= root_path %>' class='logo-link'>
      <%= image_tag(CLONE_CONFIG['LOGO_PATH'], id:'logo') %>
      <%= CLONE_CONFIG['SITE_NAME'] %>
    </a>
    <span id='user-header'>
      <% if logged_in? %>
        <!-- Logged in as <%= name_link current_user %> -->
         <!-- (<%= link_to('Log out', '/logout') %>) -->
         <div class='dropdown'>
           <%= name_link (cu = current_user) %>
           <ul class='dropdown-hidden on-right'>
             <li><%= link_to('Settings', edit_user_path(cu)) %></li>
             <li><%= link_to('Post new story', new_story_path) %></li>
             <% unless cu.tags.empty? %>
              <li><%= link_to('Favorite tags', faves_path) %></li>
             <% end %>
             <% unless cu.fave_writers.empty? %>
              <li><%= link_to('Subscriptions', subs_path) %></li>
             <% end %>
             <% unless cu.bookmarks.empty? %>
              <li><%= link_to('Bookmarks', user_bookmarks_path(cu)) %></li>
             <% end %>
             <li><%= link_to('Log out', logout_path) %></li>
           </ul>
         </div>
      <% else %>
        <%= link_to('Log In', login_path) %>
         or
        <%= link_to('Register', register_path) %>
      <% end %>
    </span>
  </div>
  <div class='full-width' id='navbar'>
    <%# link_to "Home", root_path %>
    <%= link_to "Home", home_path %>
    <%= link_to 'Tags', tags_path %>
    <%= link_to 'Stories', sources_path %>
    <%= link_to 'Users', users_path %>
    <% if is_admin? %>
      <%= link_to 'Banned Addresses', admin_banned_addresses_path %>
    <% end %>
    <span class = 'dropdown'>
      <%= link_to 'Search', search_path %>
      <ul class = 'dropdown-hidden on-left'>
        <li><%= link_to 'Stories', story_search_path %></li>
        <li><%= link_to 'Source Media', source_search_path %></li>
        <li><%= link_to 'General', search_path %></li>
      </ul>
    </span>
    <% if logged_in? %>
      <%= link_to('Post Story', new_story_path) %>
    <% end %>
  </div>
</div>

app/views/misc/_prev_next.html.erb
<div class = "next-prev">
  <% #logger.debug prev_obj.class %>
  <% #logger.debug next_obj.class %>
  <% if prev_obj %>
    <%= link_to '< Previous', prev_obj %>
  <% end %>
  <% if next_obj %>
    <%= link_to 'Next >', next_obj %>
  <% end %>
</div>

app/views/misc/_search_explanation.html.erb
<ul class='no-dec boxed'>
  <li>Text searches can use wildcards and boolean logic.</li>
  <li>By default, search terms are all required. The search
  <kbd>alpha beta</kbd> would return results that include both
  <kbd>alpha</kbd> and <kbd>beta</kbd> (as complete words).</li>
  <li>The minus sign negates a term. The search <kbd>alpha -beta</kbd> would
  return results that include
  <kbd>alpha</kbd> but not <kbd>beta</kbd> (as complete words).</li>
  <li>The pipe operator (found on most keyboards by holding down shift and
  hitting the \ key) acts as "or". The search <kbd>alpha|beta</kbd> would
  return results that
  contain the word <kbd>alpha</kbd> or the word <kbd>beta</kbd> (or both).</li>
  <li>The asterisk wildcard matches any number of characters. The search
  <kbd>alph*</kbd> would return results that contain a word starting with
  <kbd>alph</kbd>, such as <kbd>alpha</kbd>, <kbd>alphabet</kbd>, and
  <kbd>alphonse</kbd>.</li>
  <li>The question mark acts as a single-character wildcard. <kbd>fl?p</kbd>
  would match <kbd>flap</kbd>, <kbd>flip</kbd>, and <kbd>flop</kbd>, but not
  <kbd>flytrap</kbd>.</li>
  <li>Quotation marks denote an exact phrase. The search
  <kbd>"happy birthday"</kbd> would match <kbd>happy birthday</kbd> but not
  <kbd>happy fiftieth birthday</kbd>.</li>
</ul>

app/views/misc/_summary.html.erb
<% klass = obj.class %>
<% if [Bookmark, User, Story].include? klass %>
  <% temp = klass.to_s.downcase.pluralize + '/summary' %>
  <%= render temp, obj: obj %>
<% else %>
  <br> <%= name_link obj %>
<% end %>